export const FETCH_TODO_REQUEST = 'FETCH_TODO_REQUEST'
export const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS'
export const CREATE_TODO_REQUEST = 'CREATE_TODO_REQUEST'
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS'
